# Generated by Django 5.0 on 2023-12-29 21:22

import zavod.models.position
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zavod', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('task', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='contacts',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='code',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='task',
            name='count_detail',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='count_times',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='position',
            field=models.CharField(default=0, max_length=50, verbose_name=zavod.models.position.Position),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='sels',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=100),
        ),
    ]
