# Generated by Django 5.0 on 2023-12-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zavod', '0002_employee_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('task', models.CharField(max_length=100)),
            ],
        ),
    ]
