# Generated by Django 5.0 on 2023-12-19 19:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zavod', '0003_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
