# Generated by Django 5.0 on 2024-01-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zavod', '0003_alter_task_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='status',
            field=models.CharField(choices=[('moderation', 'На модерации'), ('approved', 'Одобрена')], default='moderation', max_length=20),
        ),
    ]
