# Generated by Django 5.0 on 2023-12-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zavod', '0004_data_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.RemoveField(
            model_name='task',
            name='employee',
        ),
        migrations.AddField(
            model_name='task',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
