# Generated by Django 5.0 on 2024-01-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zavod', '0004_data_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='code',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
